/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertLog {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : Time,
}
export interface EmergencyContact {
  'relationship' : string,
  'name' : string,
  'phone' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export interface _SERVICE {
  'addEmergencyContact' : ActorMethod<[EmergencyContact], undefined>,
  'getAlertLogs' : ActorMethod<[], Array<AlertLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getEmergencyContacts' : ActorMethod<[], Array<EmergencyContact>>,
  'logAlert' : ActorMethod<[number, number], undefined>,
  'removeEmergencyContact' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEmergencyContact' : ActorMethod<[bigint, EmergencyContact], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];