/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmergencyContact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const AlertLog = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  'addEmergencyContact' : IDL.Func([EmergencyContact], [], []),
  'getAlertLogs' : IDL.Func([], [IDL.Vec(AlertLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getEmergencyContacts' : IDL.Func([], [IDL.Vec(EmergencyContact)], ['query']),
  'logAlert' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'removeEmergencyContact' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEmergencyContact' : IDL.Func([IDL.Nat, EmergencyContact], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmergencyContact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const AlertLog = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    'addEmergencyContact' : IDL.Func([EmergencyContact], [], []),
    'getAlertLogs' : IDL.Func([], [IDL.Vec(AlertLog)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getEmergencyContacts' : IDL.Func(
        [],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'logAlert' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'removeEmergencyContact' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEmergencyContact' : IDL.Func([IDL.Nat, EmergencyContact], [], []),
  });
};

export const init = ({ IDL }) => { return []; };